package mods

//TODO: DO NOT DELETE OR MANUALLY EDIT THIS FILE
// This file is automatically generated for mod functionality

import (
	"MT-GO/mods/aki"
	"fmt"
	"time"
)

func Init() {
	startTime := time.Now()

	aki.Mod()

	endTime := time.Now()
	fmt.Printf("\n[MOD LOADER : COMPLETE] in %s\n", endTime.Sub(startTime))
}
