package mods

//TODO: DO NOT DELETE OR MANUALLY EDIT THIS FILE
// This file is automatically generated for mod functionality

import (
	"fmt"
	"time"
	MTGACoop"MT-GO/mods/MTGA-Coop"
)



func Init() {
	startTime := time.Now()

	MTGACoop.Mod()
        
	endTime := time.Now()
	fmt.Printf("\n[MOD LOADER : COMPLETE] in %s\n", endTime.Sub(startTime))
}