// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
package mods

import (
	EscapeFromHell "MT-GO/user/mods/EFHDev"
	EscapeFromSmell "MT-GO/user/mods/EFHLev"
	"fmt"
	"time"
)

var startTime time.Time

func Init() {
	startTime = time.Now()
	fmt.Println("\n\nInitializing ModLoader...")
	defer main()
}

func main() {
	EscapeFromHell.Mod()
	EscapeFromSmell.Mod()
	endTime := time.Now()
	fmt.Printf("Done! Finished loading mods in %s\n\n", endTime.Sub(startTime))
}
