package mods

//TODO: DO NOT DELETE OR MANUALLY EDIT THIS FILE
// This file is automatically generated for mod functionality

import (
	"MT-GO/database"
	UTD "MT-GO/user/mods/UntitledTextDocument"
	"fmt"
	"strings"
	"time"
)

var startTime time.Time
var bundlesToLoad = []string{
	"D:\\Repos\\MT-GO\\user\\mods\\UntitledTextDocument\\bundles",
}

func Init() {
	startTime = time.Now()
	fmt.Printf("\n[MODLOADER : BEGIN]\n")

	for _, path := range bundlesToLoad {
		formattedPath := strings.Replace(path, "\\\\", "\\", -1)
		database.AddModBundleDirPath(formattedPath)
	}
	UTD.Mod()

	endTime := time.Now()
	fmt.Printf("[MODLOADER : COMPLETE] %s\n", endTime.Sub(startTime))
}
