// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY EDIT.
package mods

import (
EscapeFromHell "MT-GO/user/mods/EFHDev"
	"fmt"
	"time"
)

var startTime time.Time

func Init() {
	startTime = time.Now()
	fmt.Println("		-ModLoader-\n Initilizing...")
	defer main()
}

func main() {
    EscapeFromHell.Mod()

	endTime := time.Now()
	defer fmt.Printf("Done! Finished loading mods in %s \n		-Bye Bye!-\n", endTime.Sub(startTime))
}
